sudo: required
services:
  - docker

before_install:
  - docker build -t madjava/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true madjava/react-test npm test

after_success:
  - docker build -t madjava/multi-client ./client
  - docker build -t madjava/multi-nginx ./nginx
  - docker build -t madjava/multi-server ./server
  - docker build -t madjava/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push madjava/multi-client
  - docker push madjava/multi-nginx
  - docker push madjava/multi-server
  - docker push madjava/multi-worker
